# Generated by Django 4.2.1 on 2023-08-10 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartlist',
            old_name='Cart',
            new_name='cart',
        ),
    ]
